Testing
Deepakdanger/To-do-list pull request #2
Opened 2021-08-26 10:03 UTC by Deepakdanger

Here I have done testing of function which is returning something. 👍 
- Done testing of 'createProject' function.
- Done testing of 'createTodo' function.
 Here I am doing testing via jest. 😃

2021-08-26 10:36 UTC, rindrajosia requested changes
Hi, 

Good job so far!
There are some issues to revise before continuing to the next project but hang in there and read the comments below with care. You can do it! :muscle:


## Required Changes ♻️

- [x] [REQUIRED] all functions should be tested. Please add tests for all functions inside project.js

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-08-26 10:36 UTC, rindrajosia commented on src/test/create.test.js
> +describe('Create the project', () => {
[REQUIRED] There are two ways to make test units positive and negative. Please add negative tests.

2021-08-26 10:36 UTC, rindrajosia commented on src/test/create.test.js
> +describe('Create a todo', () => {
[REQUIRED] There are two ways to make test units positive and negative. Please add negative tests.

2021-08-26 10:36 UTC, rindrajosia commented on README.md
> +"test": "jest"
- [ ] [REQUIRED] As `jest` is already installed when user uses `npm install `, I think, this information is not necessary.

2021-09-01 08:17 UTC, Deepakdanger commented
I have done all the unit tests. For testing the project.js file, I am stuck and I arrange a meeting with the senior reviewer and find out those testing is entering into a complicated integration test. so he said to do all unit tests and submit the project.

2021-09-01 09:00 UTC, oloomoses approved these changes
Hi @Deepakdanger, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Slack: Oloo Moses_
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-01 09:15 UTC, merged